### ISSUE TITLE
Use OIDC for authenticating with AWS in CI

### ISSUE THREAD

**Issue by G-Rath** [ackama/projectworks-leave-notifications#26]
Currently we're using an access key + secret to authenticate with AWS for deploying, which is easier to leak than using OIDC - this is especially important as this is a public repo.

**Comment by G-Rath** [comment]
@eoinkelly it looks like #25 has broken deployment due to not being able to auth with AWS, so it's probably worth doing this change as part of fixing that - let me know if you want to pick this up or if I should

**Comment by eoinkelly** [comment]
We could fix #25 by adding the expected secrets but I agree that OIDC is the way to go here. I'm happy if you want to pick it up

**Comment by G-Rath** [comment]
hmm @eoinkelly after starting on this, I've realised there's some additional stuff we should probably do for security if we're going to do deployments via CI given this is a public project - for the meantime I think it's best if we stick with deploying manually from local.

**Comment by eoinkelly** [comment]
I think deploying from local is totally fine for this project @G-Rath. I'm in favour of removing the deployment github actions worklflows and updating the README. Thoughts?

**Comment by G-Rath** [comment]
@eoinkelly yup sounds good to me too - and we can transfer this issue to our serverless template because we should still switch the deployment templates over to using ODIC
